all:
  children:
    routers:
      hosts:
        R1:
          ansible_host: <ROUTER_IP>
          ansible_user: admin
          ansible_password: cisco
          ansible_network_os: cisco.ios.ios
          ansible_connection: network_cli

    switches:
      hosts:
        S1:
          ansible_host: <SWITCH_IP>
          ansible_user: admin
          ansible_password: cisco
          ansible_network_os: cisco.ios.ios
          ansible_connection: network_cli



