all:
  children:
    routers:
      hosts:
        R1:
          ansible_host: 192.168.1.1
        R2:
          ansible_host: 192.168.2.1

    switches:
      hosts:
        S1:
          ansible_host: 192.168.1.10
        S2:
          ansible_host: 192.168.2.10

  vars:
    ansible_user: admin
    ansible_password: cisco
    ansible_connection: network_cli
    ansible_network_os: ios
