all:
  children:
    routers:
      hosts:
        R1:
          ansible_host: 192.168.1.1
          interfaces:
            - name: GigabitEthernet0/0/0   # router-to-router
              ipv4: 192.168.1.1
              mask: 255.255.255.0
              ipv6: 2001:DB8:1::1/64
            - name: GigabitEthernet0/0/1   # router-to-switch
              ipv4: 192.168.10.1
              mask: 255.255.255.0
              ipv6: 2001:DB8:10::1/64

        R2:
          ansible_host: 192.168.2.1
          interfaces:
            - name: GigabitEthernet0/0/0   # router-to-router
              ipv4: 192.168.1.2
              mask: 255.255.255.0
              ipv6: 2001:DB8:1::2/64
            - name: GigabitEthernet0/0/1   # router-to-switch
              ipv4: 192.168.20.1
              mask: 255.255.255.0
              ipv6: 2001:DB8:20::1/64

     switches:
      hosts:
        S1:
          ansible_host: 192.168.10.2
          ipv4_address: 192.168.10.2
          ipv4_mask: 255.255.255.0
          ipv6_address: 2001:DB8:10::2/64
          default_gateway: 192.168.10.1

        S2:
          ansible_host: 192.168.20.2
          ipv4_address: 192.168.20.2
          ipv4_mask: 255.255.255.0
          ipv6_address: 2001:DB8:20::2/64
          default_gateway: 192.168.20.1

  vars:
    ansible_user: admin
    ansible_password: cisco
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_ssh_common_args: >
      -o StrictHostKeyChecking=no
      -o UserKnownHostsFile=/dev/null
      -o KexAlgorithms=+diffie-hellman-group14-sha1
      -o HostKeyAlgorithms=+ssh-rsa
