all:
  children:
    routers:
      hosts:
        R1:
          ansible_host: 192.168.1.1
          interfaces:
            - name: Serial0/1/0
              ipv4: 10.0.0.1
              mask: 255.255.255.252
              ipv6: 2001:DB8:1::1/64
            - name: GigabitEthernet0/0/0
              ipv4: 192.168.1.1
              mask: 255.255.255.0
              ipv6: 2001:DB8:10::1/64

        R2:
          ansible_host: 192.168.2.1
          interfaces:
            - name: Serial0/1/0
              ipv4: 10.0.0.2
              mask: 255.255.255.252
              ipv6: 2001:DB8:1::2/64
            - name: GigabitEthernet0/0/0
              ipv4: 192.168.2.1
              mask: 255.255.255.0
              ipv6: 2001:DB8:20::1/64

    switches:
      hosts:
        S1:
          ansible_host: 192.168.1.10
          ipv4_address: 192.168.1.10
          ipv4_mask: 255.255.255.0
          ipv6_address: 2001:DB8:1::10/64
          default_gateway: 192.168.1.1

        S2:
          ansible_host: 192.168.2.10
          ipv4_address: 192.168.2.10
          ipv4_mask: 255.255.255.0
          ipv6_address: 2001:DB8:2::10/64
          default_gateway: 192.168.2.1

  vars:
    ansible_user: admin
    ansible_password: cisco
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_ssh_common_args: >
      -o StrictHostKeyChecking=no
      -o UserKnownHostsFile=/dev/null
      -o KexAlgorithms=+diffie-hellman-group14-sha1
      -o HostKeyAlgorithms=+ssh-rsa
